import express from 'express';
import cors from 'cors';
import chatRoutes from './routes/chat';
import contentRoutes from './routes/content';
import leadRoutes from './routes/lead';
import customerRoutes from './routes/customer';
import deployRoutes from './routes/deploy';
import renderRoutes from './routes/render';
import generateRoutes from './routes/generate';
import branchRoutes from './routes/branch';
const app = express();
const PORT = parseInt(process.env.PORT || '3001');
const origins = process.env.FRONTEND_URL?.split(',').map(u => u.trim()) || ['http://localhost:3000'];
console.log('CORS origins:', origins);
app.use(cors({ origin: origins, credentials: true, methods: ['GET','POST','PATCH','PUT','DELETE','OPTIONS'], allowedHeaders: ['Content-Type','Authorization'] }));
app.use(express.json({ limit: '10mb' }));
app.get('/health', (_req, res) => { res.json({ status: 'ok', service: 'nyn-impact-api', ts: new Date().toISOString() }); });
app.use('/api/chat', chatRoutes);
app.use('/api/content', contentRoutes);
app.use('/api/lead', leadRoutes);
app.use('/api/customer', customerRoutes);
app.use('/api/deploy', deployRoutes);
app.use('/api/render', renderRoutes);
app.use('/api/generate', generateRoutes);
app.use('/api/branch', branchRoutes);
app.listen(PORT, '0.0.0.0', () => { console.log('NYN Impact API running on port ' + PORT); });
